### ISSUE TITLE
Add remarketing option

### ISSUE THREAD

**Issue by andkn** [tollwerk/TYPO3-ext-tw_googleanalytics#5]
Would be great to have the possibility to enable remarketing/displayfeatures [1] as you can see here.

[1] https://support.google.com/analytics/answer/2444872#trackingcode

**Comment by jkphl** [comment]
Hi @andkn,

I added a new option (`settings.features.advertising` respectively the constant `settings.advertising`) which should enable the remarketing and advertising reporting features for both the classic Google Analytics as well as for Universal Analytics.

As I don't have any experience with this on the GA side of things, I'd like to ask you to play around with it now and let me know if it works. You will need to install the latest GitHub resources in order to try out the new features. I'll release an official TER version as soon as you confirm that it's functional. Thanks for your support! :)

Cheers,
Joschi

**Comment by jkphl** [comment]
@andkn Did you ever have the chance to check whether my additions work for you as expected? As you didn't respond for a long time I'll close this issue for now, but please feel free to get back to me in case of problems or further questions!
